@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "programming.technology.universitystructure.UniversityStructureController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1679325940 { 
   	label=technology
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_548097731 { 
   	label=universitystructure
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Department813707368[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Department</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   components: List&lt;UniversityComponent&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addComponent(component: UniversityComponent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeComponent(component: UniversityComponent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Faculty813707368[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Faculty</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   components: List&lt;UniversityComponent&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addComponent(component: UniversityComponent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeComponent(component: UniversityComponent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Group813707368[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Group</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addComponent(component: UniversityComponent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeComponent(component: UniversityComponent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UniversityComponent813707368[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UniversityComponent</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   name: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addComponent(component: UniversityComponent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeComponent(component: UniversityComponent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UniversityStructureController1714556536[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UniversityStructureController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   addButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nameField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   remoteButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   treeView: TreeView&lt;UniversityComponent&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- addElement()</TD></TR>
<TR><TD ALIGN="LEFT" >- displayWarningMessage(text: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ initialize(url: URL, resourceBundle: ResourceBundle)</TD></TR>
<TR><TD ALIGN="LEFT" >- removeElement()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Department813707368 -> UniversityComponent813707368[label="components
[0..*]"];
Faculty813707368 -> UniversityComponent813707368[label="components
[0..*]"];
UniversityComponent813707368 -> Department813707368[arrowhead=none, arrowtail=empty, dir=both];
UniversityComponent813707368 -> Faculty813707368[arrowhead=none, arrowtail=empty, dir=both];
UniversityComponent813707368 -> Group813707368[arrowhead=none, arrowtail=empty, dir=both];
UniversityStructureController1714556536 -> UniversityComponent813707368[label="treeView
[0..1]"];
    
}
@enduml