@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "tasks.task2.models.Shape",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_110132045 { 
   	label=task2
	labeljust=l
	fillcolor="#ececec"
   
   subgraph cluster_1540536118 { 
   	label=controllers
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   MainController571690198[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MainController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   backShapeButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   canvas: Canvas [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   descLabel: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fileChooser: FileChooser [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   gc: GraphicsContext [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nameShapeTextField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   openMenuItem: MenuItem [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   saveMenuItem: MenuItem [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   saveShapesButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   shapes: Deque&lt;Shape&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- backShapeHandler(event: MouseEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >- displayWarningMessage(text: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- drawShapeHandler(event: MouseEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >- drawShapesOnCleanCanvas()</TD></TR>
<TR><TD ALIGN="LEFT" >+ initialize(url: URL, resourceBundle: ResourceBundle)</TD></TR>
<TR><TD ALIGN="LEFT" >- openFileHandler(actionEvent: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >- saveFileHandler(actionEvent: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_677622827 { 
   	label=models
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Circle4463243[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Circle</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ discriptor(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ draw(gc: GraphicsContext)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Rectangle4463243[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Rectangle</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ discriptor(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ draw(gc: GraphicsContext)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Shape4463243[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Shape</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   fillColor: Color [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   height: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   strokeColor: Color [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   width: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   x: double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   y: double [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ discriptor(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ draw(gc: GraphicsContext)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Triangle4463243[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Triangle</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ discriptor(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ draw(gc: GraphicsContext)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
MainController571690198 -> Shape4463243[label="shapes
[0..1]"];
Shape4463243 -> Circle4463243[arrowhead=none, arrowtail=empty, dir=both];
Shape4463243 -> Rectangle4463243[arrowhead=none, arrowtail=empty, dir=both];
Shape4463243 -> Triangle4463243[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml